<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 40px;
                font-weight: 200;
                margin-bottom: 0;
            }
            ul {
                list-style-type: none;
            }
            .answers {
                width:150px;
                margin:0 auto;

            }
            .answers p {
                text-align: left;
            }
        </style>
        <script type="text/javascript">
            $(document).ready(function () {

                $("#questionForm").submit(function (event) {
                    if (!event.target.answer.value) {
                        $("#message").html("Must select an answer");
                        return false;
                    } else {
                        $("#message").html("");
                        return true;
                    } 
                    
                })

            })
        </script>

    </head>
    <body>
        <h1>Career Interest Assessment</h1>
            <ul>
            <?php for ($i = 0; $i < count($score); $i++) {
                echo "<li>" . $score[$i]['name'] . ": " . $score[$i]['score'] . "</li>";
            } 
            ?>
            </ul>
            <p><a href="/logout">Logout</a></p>
    </body>
</html>
